### ISSUE TITLE
Core dump on Python3

### ISSUE THREAD

**Issue by Lothiraldan** [minrk/wurlitzer#10]
Hello, first of all, thank you for the `wurlitzer` library.

I'm trying to use it to capture the stdout and stderr from a library that should works in Python 2 and Python 3. In Python 2, this test file works well:

```
from wurlitzer import pipes

def test():
    print("Test")

with pipes() as (out, err):
    test()
```

But on Python 3, it very easily crash with this output:

```
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted (core dumped)
```

After digging, I think I've hit this Python bug: https://bugs.python.org/issue18748

My core dump stack trace looks similar:

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f3527e50f5d in __GI_abort () at abort.c:90
#2  0x00007f3527e9928d in __libc_message (action=action@entry=(do_abort | do_backtrace), fmt=fmt@entry=0x7f3527fbe7fe "%s") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f3527e992e2 in __GI___libc_fatal (message=message@entry=0x7f3528db34d8 "libgcc_s.so.1 must be installed for pthread_cancel to work\n") at ../sysdeps/posix/libc_fatal.c:191
#4  0x00007f3528db181f in pthread_cancel_init () at ../sysdeps/nptl/unwind-forcedunwind.c:64
#5  0x00007f3528db1924 in _Unwind_ForcedUnwind (exc=0x7f35275dcd70, stop=stop@entry=0x7f3528daf780 <unwind_stop>, stop_argument=0x7f35275dbf20) at ../sysdeps/nptl/unwind-forcedunwind.c:126
#6  0x00007f3528daf900 in __GI___pthread_unwind (buf=<optimized out>) at unwind.c:121
#7  0x00007f3528da6a25 in __do_cancel () at pthreadP.h:297
#8  __pthread_exit (value=<optimized out>) at pthread_exit.c:28
#9  0x000000000043e7dc in PyThread_exit_thread ()
#10 0x000000000058e335 in ?? ()
#11 0x00007f3528da57fc in start_thread (arg=0x7f35275dc700) at pthread_create.c:465
#12 0x00007f3527f2cb0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

The Python bug doesn't mention a workaround that could be done on the code side, unfortunately.

I was wondering if you had an idea how to update the code to avoid it or just letting you know that the library is crashing on Python 3.

**Comment by minrk** [comment]
Can you test #10? I was able to reproduce the issue (though only ~1% of the time), and #11 appears to fix it for me.

**Comment by Lothiraldan** [comment]
That seems better, I will try running it 10000 times to see if it crash.

**Comment by Lothiraldan** [comment]
After 10000 runs and no crash, I think we can safely say that it fixes the bug. Thank you very much sir for the very prompt answer, I owe you a beer. Are you going to Fosdem in February?

**Comment by minrk** [comment]
Thanks! I've pushed out 1.0.1 with this fix. I won't be at fosdem, perhaps another time.
